import type { Metadata } from "next";
import Header from "@/components/navigation/Header";
import SideNav from "@/components/navigation/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="min-h-screen bg-delivery-bg">
        <Header />
        <div className="flex">
          <SideNav />
          <main className="flex-1 mt-[72px] ml-54">{children}</main>
        </div>
      </div>
    </>
  );
}
